(asdf:defsystem "cl-swayipc"
  :description "ASD file generated by Ross' mkproject script."
  :version "0.1.0"
  :author "Ross Edwards <redwards64@hotmail.com>"
  :license "BSD"
  :source-control (:git "")

  :depends-on (#:sb-bsd-sockets
               #:jzon)
  :components ((:module "src"
                :serial t
                :components ((:file "cl-swayipc")))))
