{
  description = "Flake generated by Ross' mkproject script.";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    { nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs { inherit system; };
      in
      {
        devShell = pkgs.mkShell {
          nativeBuildInputs = with pkgs; [
            roswell
            (sbcl.withPackages (ps: with ps; [ com_dot_inuoe_dot_jzon ]))
          ];
        };
      }
    );
}
